name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - scala213

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v3.0

      - name: Check code format
        run: sbt scalafmtCheck

      - name: Build and test
        run: sbt test

      - name: Make sure we can deploy the app
        run: sbt dist

